add paraview

diff --git a/paraview/paraview.SlackBuild b/paraview/paraview.SlackBuild
--- a/paraview/paraview.SlackBuild
+++ b/paraview/paraview.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-# Slackware build script for vtk
+# Slackware build script for ParaView
 
-# Copyright 2013 Youjie Zhou <jmpopush AT gmail DOT com>
+# Copyright 2014 Youjie Zhou <jmpopusth AT gmail DOT com>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,47 +22,52 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PRGNAM=vtk
-PKGNAM=VTK
-VERSION=${VERSION:-6.0.0}
+PRGNAM=paraview
+VERSION=${VERSION:-"4.0.1"}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
-
-if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
-    arm*) ARCH=arm ;;
-    *) ARCH=$( uname -m ) ;;
-  esac
-fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) ARCH=i486 ;;
+    arm*) ARCH=arm ;;
+       *) ARCH=$( uname -m ) ;;
+  esac
+fi
+
+# Change source package name
+if [ "$ARCH" = "x86_64" ]; then
+  SRCARCH="64bit"
   LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "arm" ]; then
+  printf "\n$ARCH is unsupported for ParaView...\n\n"
+  exit 1
 else
-  SLKCFLAGS="-O2"
+  SRCARCH="32bit"
   LIBDIRSUFFIX=""
 fi
 
-set -e
+# Construct the name of the tarball
+TARNAME="ParaView-${VERSION}-Linux-${SRCARCH}"
+if [ ! -r $TARNAME.tar.gz ]; then
+  echo "$TARNAME not found"
+  exit 1
+fi
+
+set -eu
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PKGNAM$VERSION # correct source code folder name is VTK6.0.0
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
-cd $PKGNAM$VERSION
+rm -rf $TARNAME
+tar xvf $CWD/$TARNAME.tar.gz
+
+cd $TARNAME
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -70,29 +75,26 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir -p build
-cd build
-  cmake \
-    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_INSTALL_PREFIX=/usr \
-    -DCMAKE_BUILD_TYPE=Release ..
-  make -j4
-  make install DESTDIR=$PKG
-cd ..
-
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+find . -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-# move lib/ to the proper location
-if [ "$ARCH" = "x86_64" ]; then
-  mv $PKG/usr/lib $PKG/usr/lib$LIBDIRSUFFIX
-fi
+mkdir -p $PKG/opt/$PRGNAM$VERSION
+mv * $PKG/opt/$PRGNAM$VERSION/
+
+# Because paraview uses relative path in its codes, we have to create
+# small launcher scripts 
+mkdir -p $PKG/usr/bin
+cd $PKG/usr/bin/
+for FILE in $PKG/opt/$PRGNAM$VERSION/bin/* ; do
+    NAME=$(basename $FILE)
+    echo ../../opt/$PRGNAM$VERSION/bin/$NAME > $NAME
+    chmod +x $NAME ;
+done
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  $TMP/$PKGNAM$VERSION/Examples \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cd $PKG/opt/$PRGNAM$VERSION/
+mv doc/* $PKG/usr/doc/$PRGNAM-$VERSION/
+rm -rf doc/
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
